### ISSUE TITLE
Update project website: README

### ISSUE THREAD

**Issue by Na-Nazhou** [AY1920S1-CS2103T-T13-4/main#10]

**Comment by Na-Nazhou** [comment]
Acknowledge the original source of the code i.e. AddressBook-Level3 project created by SE-EDU initiative at https://se-education.org

**Comment by Na-Nazhou** [comment]
- remove references to addressbook-level2
- remove Learning Outcomes
- mention your target users
- add a marketing blurb

**Comment by Na-Nazhou** [comment]
Do we need to mention the target user in README?

**Comment by dorcastan** [comment]
> Do we need to mention the target user in README?

We did mention "for people who love to type", which technically counts as a target user... Do we need to make it more explicit?

**Comment by dorcastan** [comment]
Closed for v1.1. Can make further changes in future updates.
