### ISSUE TITLE
Update SampleDataUtil

### ISSUE THREAD

**Issue by Na-Nazhou** [AY1920S1-CS2103T-T13-4/main#156]
### Folder structure with bookmarks:
* ROOT
    * [User Guide](https://ay1920s1-cs2103t-t13-4.github.io/main/)
* School
    * General
        * [Luminus](https://luminus.nus.edu.sg/)
        * [NUSMods](https://nusmods.com/timetable/sem-1)
        * [NUS Library](https://libportal.nus.edu.sg/frontend/index)
        * [BComp CS Curriculum](https://www.comp.nus.edu.sg/programmes/ug/cs/curr/)
        * [BComp CS Focus Areas](https://www.comp.nus.edu.sg/programmes/ug/focus/)
    * Modules
        * [CS2103 Textbook](https://nus-cs2103-ay1920s1.github.io/website/se-book-adapted/index.html)
        * [CS2103 Pollev](https://pollev.com/softeng)
        * [CS2103T Team GitHub](https://github.com/AY1920S1-CS2103T-T13-4/main/)
        * [PlantUML mix different diagram type elements](https://stackoverflow.com/questions/54020731/how-to-mix-different-plantuml-diagram-type-elements)
        * [Python3 Tutorial](https://docs.python.org/3/tutorial/)
        * [PostgreSQL Documentation](https://www.postgresql.org/docs/current/tutorial.html)
        * [Java13 API](https://docs.oracle.com/en/java/javase/13/docs/api/index.html)
        * [Latex](https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes)
        * [CS3243 Textbook](http://aima.cs.berkeley.edu/)
        * [IntelliJ IDEA Tips and Tricks](https://www.youtube.com/watch?v=9AMcN-wkspU) 
        * [Bayesian Networks intro](https://towardsdatascience.com/introduction-to-bayesian-networks-81031eeed94e)
* Interview
    * [Tech Interview Handbook](https://yangshun.github.io/tech-interview-handbook/)
    * [LeetCode](https://leetcode.com/)
    * [Get that job at Google](http://steve-yegge.blogspot.com/2008/03/get-that-job-at-google.html)
* Entertainment
    * Videos
        * [PianoGuys Rewrite the Stars](https://www.youtube.com/watch?v=5cINJwaAn4Y)
    * [I tried to reset my alarm clock](https://devblogs.microsoft.com/oldnewthing/20191104-01/?p=103052)
    * [Why I left Google to join Grab](https://medium.com/@steve.yegge/why-i-left-google-to-join-grab-86dfffc0be84)

### Bookmarks
* [User Guide](https://ay1920s1-cs2103t-t13-4.github.io/main/) (tags: Favorite, Help; folder: ROOT; remark: User guide for Mark)
* [Luminus](https://luminus.nus.edu.sg/) (tags: NUS; folder: General)
* [NUSMods](https://nusmods.com/timetable/sem-1) (tags: NUS; folder: General; remark: Timetable planning)
* [CS2103 Textbook](https://nus-cs2103-ay1920s1.github.io/website/se-book-adapted/index.html) (tags: NUS; folder: Modules; remark:-)
* [CS2103 Pollev](https://pollev.com/softeng) (tags: CS2103T, NUS; folder: Modules; remark: Used for CS2103T in-lecture quiz)
* [Python3 Tutorial](https://docs.python.org/3/tutorial/) (tags: Python, ProgrammingHelp; folder: Modules)
* [PostgreSQL Documentation](https://www.postgresql.org/docs/current/tutorial.html)(tags: CS2102, PostgreSQL; folder: Modules)
* [Java13 API](https://docs.oracle.com/en/java/javase/13/docs/api/index.html)(tags: CS2030, CS2040, CS2103, Java, ProgrammingHelp; folder: Modules)
* [Latex](https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes)(folder: Modules)
* [NUS Library](https://libportal.nus.edu.sg/frontend/index) (tags: NUS; folder: General)
* [Tech Interview Handbook](https://yangshun.github.io/tech-interview-handbook/) (tags: ProgrammingHelp; folder: Interview)
* [LeetCode](https://leetcode.com/) (tags: ProgrammingHelp; folder: Interview)
* [CS3243 Textbook](http://aima.cs.berkeley.edu/) (tags: CS3243, NUS; folder: Modules)
* [CS2103T Team GitHub](https://github.com/AY1920S1-CS2103T-T13-4/main/) (tags: CS2103T, NUS; folder: Modules; Remark: Mark the bookmark manager)
* [PlantUML mix different diagram type elements](https://stackoverflow.com/questions/54020731/how-to-mix-different-plantuml-diagram-type-elements) (tags: StackOverflow, PlantUML, ProgrammingHelp; folder: Modules; Remark: -)
* [PianoGuys Rewrite the Stars](https://www.youtube.com/watch?v=5cINJwaAn4Y) (tags: Music, Video; folder: Videos; Remark: from The Greatest Showman)
* [IntelliJ IDEA Tips and Tricks](https://www.youtube.com/watch?v=9AMcN-wkspU) (tags: Video, ProgrammingHelp; folder: Modules; Remark: for reference, watch on 2x speed)
* [BComp CS Curriculum](https://www.comp.nus.edu.sg/programmes/ug/cs/curr/) (tag: Favorite; folder: General; Remark: Contains modules needed for graduation)
* [BComp CS Focus Areas](https://www.comp.nus.edu.sg/programmes/ug/focus/) (tag: -; folder: General; Remark: ?)
* [Get that job at Google](http://steve-yegge.blogspot.com/2008/03/get-that-job-at-google.html) (tag: Blog; folder: Interview; Remark: must read)
* [I tried to reset my alarm clock](https://devblogs.microsoft.com/oldnewthing/20191104-01/?p=103052) (tags: Funny, Blog, IoT; folder: Entertainment; Remark: -)
* [Why I left Google to join Grab](https://medium.com/@steve.yegge/why-i-left-google-to-join-grab-86dfffc0be84) (tag: Blog; folder: Entertainment; Remark: insights into Google innovation culture and Grab's potential)
* [Bayesian Networks intro](https://towardsdatascience.com/introduction-to-bayesian-networks-81031eeed94e) (tag: CS3243; folder: Modules; Remark: for last assignment of the sem)

Actually most of these are not cache-friendly... will try to look for other pages

**Comment by Na-Nazhou** [comment]
Ideally we should have around 10 bookmarks.
At least 3 with multiple tags
At least 1 without any tag
At least 3 without cache (so user can try caching it)
At least 3 with reminder
At least 3 folders (folder structure should be reasonably complex)

**Comment by dorcastan** [comment]
Some suggestions! Based on the tests I've been using around.

Folder structure:
* School
    * General
    * Modules
* Entertainment
    * Videos

Bookmarks:
* [CS2103T Team GitHub](https://github.com/AY1920S1-CS2103T-T13-4/main/) (tags: CS2103T, NUS; folder: Modules; Remark: Mark the bookmark manager)
* [PlantUML mix different diagram type elements](https://stackoverflow.com/questions/54020731/how-to-mix-different-plantuml-diagram-type-elements) (tags: StackOverflow, PlantUML, ProgrammingHelp; folder: Modules; Remark: -)
* [PianoGuys Rewrite the Stars](https://www.youtube.com/watch?v=5cINJwaAn4Y) (tags: Music, Video; folder: Videos; Remark: from The Greatest Showman)
* [IntelliJ IDEA Tips and Tricks](https://www.youtube.com/watch?v=9AMcN-wkspU) (tags: Video, ProgrammingHelp; folder: Modules; Remark: for reference, watch on 2x speed)
* [BComp CS Curriculum](https://www.comp.nus.edu.sg/programmes/ug/cs/curr/) (tag: Favorite; folder: General; Remark: Contains modules needed for graduation)
* [BComp CS Focus Areas](https://www.comp.nus.edu.sg/programmes/ug/focus/) (tag: Favorite; folder: General; Remark: ?)

Autotags:
* Video (`u/youtube.com`)
* ProgrammingHelp (`u/stackoverflow.com/questions`)
* NUS (`f/School f/General f/Modules`)

**Comment by dorcastan** [comment]
Will update this at `0000` tonight – before then, can add on to (edit) the original issue!

**Comment by dorcastan** [comment]
Sample reminders:
* "Revise for finals" -- [CS2103T Textbook](https://nus-cs2103-ay1920s1.github.io/website/se-book-adapted/index.html), 22/11/2019 1200
* "Start planning next sem's timetable" -- [NUSMods](https://nusmods.com/), 7/12/2019 1000
*  default value ("Open") -- [BComp CS Curriculum](https://www.comp.nus.edu.sg/programmes/ug/cs/curr/), 7/12/2019 1000

**Comment by dorcastan** [comment]
Possible things to cache:
* [LaTeX Tutorial](https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes)
* [SICP Introduction](https://sicp.comp.nus.edu.sg/chapters/1)
* [Why I left Google to join Grab](https://medium.com/@steve.yegge/why-i-left-google-to-join-grab-86dfffc0be84) (or any other Medium post)

**Comment by dorcastan** [comment]
Need to add cache and more autotags before v1.4 submission.
