### ISSUE TITLE
Replace string with Java URL in Url class

### ISSUE THREAD

**Issue by Na-Nazhou** [AY1920S1-CS2103T-T13-4/main#78]
Nice to have.

First need to check whether Java URL is suitable first.
This should not affect other functionalities since only the underlying implementation of Url class will be changed.

**Comment by Na-Nazhou** [comment]
I can do it over the weekend since i have completed most of my 1.2 stuff :) @dorcastan

**Comment by dorcastan** [comment]
Okay! Thanks @Na-Nazhou. From the Java API for [`java.net.URL`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/URL.html), it looks like `URI` might be needed too to handle the encoding/ decoding of characters.

**Comment by Na-Nazhou** [comment]
> Okay! Thanks @Na-Nazhou. From the Java API for [`java.net.URL`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/URL.html), it looks like `URI` might be needed too to handle the encoding/ decoding of characters.

I tried to replace it with URL but it seems that both `toUri()` and `new URL()` are not sufficient to validate the URL unless we try to call `openConnection()` every time we instantiate a Url which would require network connection. 
Even if we replace string with URL, I guess we still need to keep those regex for validation. I think it will only be useful if you need some methods provided by the URL class (like `getHost(), getPath()`) for auto-tagging. What do you think?
