### ISSUE TITLE
Change bookmark display in hierarchy

### ISSUE THREAD

**Issue by openorclose** [AY1920S1-CS2103T-T13-4/main#80]
![image](https://user-images.githubusercontent.com/42093424/66564289-3e086180-eb92-11e9-95d1-54a0108d13c6.png)

Maybe we can omit the `folder` field from bookmarks since we have shown the folder structure, but we change that next time:)

_Originally posted by @Na-Nazhou in https://github.com/AY1920S1-CS2103T-T13-4/main/pull/66#issuecomment-540523057_

Other than this, we probably need a better way to display them.

**Comment by Na-Nazhou** [comment]
- [ ] Place the folder tree view inside the dashboardPanel.
