### ISSUE TITLE
Bookmark can still be added even though folder does not exist

### ISSUE THREAD

**Issue by Na-Nazhou** [AY1920S1-CS2103T-T13-4/main#85]
#### Step(s) to reproduce:
- Type `add u/http://www.google.com n/YouTube f/haha`
- Expected: automatically create the folder `haha` / throw exception
- Actual: Bookmark is successfully added even though I do not have folder called `haha` and folder `haha` is not present in the folder structure.
![image](https://user-images.githubusercontent.com/42093424/66693325-4075d300-ecda-11e9-92af-7db39e2337cf.png)

**Comment by Na-Nazhou** [comment]
Suggestion 1: allow automatic creation of folder under ROOT if the folder is not present in the current folder structure 
Suggestion 2: throw exception and ask the user to create the folder first if the folder does not exist

**Comment by dorcastan** [comment]
@openorclose Any progress on this?

**Comment by openorclose** [comment]
> @openorclose Any progress on this?

nope, i'll do it now
