### ISSUE TITLE
Do we clear folders when clearing bookmarks?

### ISSUE THREAD

**Issue by Na-Nazhou** [AY1920S1-CS2103T-T13-4/main#86]
I think it is nice to have. Cos we have a `clear` command to clear all the bookmarks but the folders are not cleared. So I think it is better to either clear the folders together with the bookmarks or have a separate command to clear all the folders.

Normally the user types `clear` only when they want to start from a clean slate right?
Personally I feel we can just clear all the folders when the user types `clear`.

This applies to other modules as well, i.e. reminders, annotations, cache

**Comment by dorcastan** [comment]
I agree that it is useful to be able to clear all of Mark's data! But it would also be nice to have separate commands to clear individual modules, like reminders or cache.

If we do this, I can see two possible types of command syntax:
1. Use `clear` to clear all data, and add a parameter (e.g. `clear reminders`, `clear bookmarks`) to clear individual modules.
2. Use `clear all` to clear all data, and let individual modules be cleared using their command keywords e.g. `reminder clear`, `annotate clear`. 
In this case, we might have to define `clear` as clearing bookmarks only.

I'm not sure which option is preferable, so... should we change the function of the command `clear`?

**Comment by dorcastan** [comment]
`clear` clears all of Mark's data
